name: Generate PR Description

on:
  pull_request:
    types: [opened, edited, synchronize]

jobs:
  generate-pr-description:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Generate PR diff content
        run: |
          echo "Running git diff between the PR branch and main..."
          git diff origin/main...HEAD > diff_content.txt
          echo "Diff content saved to diff_content.txt"

      - name: Set up Python Environment
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests  # Install requests library

      - name: Generate PR Description
        env:
          LLAMA_API_URL: https://ea9f-129-210-115-225.ngrok-free.app/generate
        run: |
          echo "Running main.py with diff_content.txt"
          python main.py "diff_content.txt" "${{ github.event.pull_request.number }}"


      - name: Capture PR Description Output
        id: read_pr_description
        run: |
          pr_body=$(cat pr_description.txt)
          echo "PR_BODY<<EOF" >> $GITHUB_ENV
          echo "$pr_body" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: Update Pull Request Body
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            github.rest.pulls.update({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.payload.pull_request.number,
              body: process.env.PR_BODY
            });
