name: "Auto-Generate PR Description with Local Ollama API"

on:
  pull_request:
    types: [opened, synchronize]  # Trigger on new or updated PRs

jobs:
  generate-pr-description:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 1: Capture the diff output in an environment variable
      - name: Generate PR diff content
        id: generate_diff
        run: |
          echo "DIFF_CONTENT<<EOF" >> $GITHUB_ENV
          git diff >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      # Step 2: Set up Python Environment and Install Dependencies
      - name: Set up Python Environment
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Step 3: Run main.py with the diff content from the environment variable
      - name: Generate PR Description
        id: generate_pr_description
        env:
          LLAMA_API_URL: "https://abcd1234.ngrok.io/generate"  # Replace with your ngrok URL
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DIFF_CONTENT: ${{ env.DIFF_CONTENT }}
        run: |
          python main.py "${DIFF_CONTENT}" "${{ github.event.pull_request.number }}"
        shell: bash

      # Step 4: Update the Pull Request Body directly
      - name: Update Pull Request Body
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            github.rest.pulls.update({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.payload.pull_request.number,
              body: `${{ steps.generate_pr_description.outputs.pr_body }}`
            });
