name: "Auto-Generate PR Description with Local Ollama API"

on:
  pull_request:
    types: [opened, synchronize]  # Trigger when a PR is created or updated

jobs:
  generate-pr-description:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python Environment
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Generate PR Description
        env:
          LLAMA_API_URL: "https://97c8-2601-647-4601-2b0-6d8c-447a-3da8-a521.ngrok-free.app"  # Replace with your ngrok URL
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          python main.py --diff_file diff.txt --output_file output.txt --pr_file pr.json

      - name: Update Pull Request Body
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const fs = require('fs');
            const pr_body = fs.readFileSync('output.txt', 'utf8');
            github.rest.pulls.update({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.payload.pull_request.number,
              body: pr_body
            });
