name: "Auto-Generate PR Description with Local Ollama API"

on:
  pull_request:
    types: [opened, synchronize]  # Trigger on new or updated PRs

jobs:
  generate-pr-description:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Fetch all history to allow diffing with main

      # Step 1: Capture the diff output as a base64-encoded environment variable
      - name: Generate PR diff content
        id: generate_diff
        run: |
          echo "Running git diff between the PR branch and main..."
          DIFF_CONTENT=$(git diff origin/main...HEAD | base64)  # Encode diff as base64
          echo "Diff content captured (base64-encoded):"
          echo "$DIFF_CONTENT"
          
          # Set DIFF_CONTENT as a base64-encoded environment variable
          echo "DIFF_CONTENT=$DIFF_CONTENT" >> $GITHUB_ENV

      # Step 2: Set up Python Environment and Install Dependencies
      - name: Set up Python Environment
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Step 3: Run main.py, decoding DIFF_CONTENT in the script
      - name: Generate PR Description
        id: generate_pr_description
        env:
          LLAMA_API_URL: "https://abcd1234.ngrok.io/generate"  # Replace with your ngrok URL
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DIFF_CONTENT: ${{ env.DIFF_CONTENT }}
        run: |
          echo "Decoding DIFF_CONTENT passed to main.py:"
          DECODED_DIFF_CONTENT=$(echo "${DIFF_CONTENT}" | base64 --decode)  # Decode diff content
          echo "$DECODED_DIFF_CONTENT"  # Print the decoded DIFF_CONTENT for debugging
          python main.py "$DECODED_DIFF_CONTENT" "${{ github.event.pull_request.number }}"
        shell: bash

      # Step 4: Update the Pull Request Body directly
      - name: Update Pull Request Body
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            github.rest.pulls.update({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.payload.pull_request.number,
              body: `${{ steps.generate_pr_description.outputs.pr_body }}`
            });
